Repository Vizzuality/front-end-scaffold, pull requests merged in 2022-08, with the labels that each got.

#71 React map gl initial view state
  src/components/map/component.stories.tsx
  src/components/map/component.tsx
  src/components/map/layers.ts
  src/components/map/types.d.ts
Labels: enhancement

#62 Floating UI components
  package.json
  src/components/confirmation-prompt/component.stories.tsx
  src/components/confirmation-prompt/component.tsx
  src/components/modal/component.stories.tsx
  src/components/modal/component.tsx
  src/components/modal/constants.ts
  src/components/modal/content/component.tsx
  src/components/modal/content/constants.ts
  src/components/modal/content/types.ts
  src/components/modal/types.d.ts
  src/components/tooltip/arrow/component.tsx
  src/components/tooltip/arrow/index.ts
  src/components/tooltip/arrow/types.d.ts
  src/components/tooltip/component.stories.tsx
  src/components/tooltip/component.tsx
  src/components/tooltip/types.d.ts
  yarn.lock
Labels: enhancement, work-in-progress

#75 improve env sample and add envs documentation to readme
  .env.default
  .env.sample
  README.md
  docs/install.stories.mdx
  src/lib/analytics/ga.ts
Labels: documentation, enhancement, ready to review

#77 404 and 500 page
  src/pages/404.tsx
  src/pages/500.tsx
Labels: enhancement, ready to review

#80 Third party scripts: loaded by accepted cookie
  package.json
  src/components/cookies/component.stories.tsx
  src/components/cookies/component.tsx
  src/components/cookies/index.ts
  src/components/cookies/types.d.ts
  src/containers/third-party/component.tsx
  src/containers/third-party/index.ts
  src/hooks/modals/index.tsx
  src/hooks/modals/types.d.ts
  src/lib/analytics/ga.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/privacy-policy.tsx
  yarn.lock
Labels: enhancement, ready to review
